### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by legacyxdd** [r2hu1/MySocials#3]
Hey, amazing project! I just have few questions I would be really happy if you can answer.
1. How can we add view count in users profiles and also add a toggle button in dashboard that enables/disables showing the view count on users site?
2. How can we add an input to dashboard that will allow users to upload an image as a link (like https://c.tenor.com/zzz/tenor.gif) which will set their background (basically custom backgrounds)?

**Comment by r2hu1** [comment]
to add a view counter basically analysis just add a new schema in property in userSchema i.e profileViews and update its value i.e currentview + 1 whenever new user visits its page make sure to add cookie to make it unique per user 

and about profile image just update the value of the image:{
        type: String,
        max:4000
    }, as you need 


pretty simple and i am gonna add detailed views analysis in some days

**Comment by r2hu1** [comment]
misunderstood but its pretty simple you need to add a new value in the user schema and add a div with img in it and in the dashboard add a input to update the value and the img src thats it

**Comment by r2hu1** [comment]
yah i know and fixed it

**Comment by r2hu1** [comment]
yah fixing it

**Comment by r2hu1** [comment]
> By the way I want to mention a small but important bug let's say my username is test, and I change it to test1, I now own both test and test1 links which results in being able to claim unlimited links. Also when I change to test1 it keeps displaying the name as test in the dashboard

fixed!!

**Comment by r2hu1** [comment]
in `/app/(user)/_components
/ManageForm.jsx` theres a func that reloads page `setTimeout(() => {
                        location.reload();
                    }, 1000)`  
might making trouble try removing it or change the timeout delay

**Comment by r2hu1** [comment]
did you added img tag with proper fetching and assigning src? in the UserSocials.jsx?

**Comment by r2hu1** [comment]
pretty easy fix just add a logic, if theres .mp4 in the `back` i.e background url render video eliment else img

{back.includes(".mp4") : (<video do stuff here/>) ? (<img do stiff here/>)}

**Comment by r2hu1** [comment]
it will work ig

**Comment by r2hu1** [comment]
haha mistakenly swapped the place 

glad it worked 😁

**Comment by r2hu1** [comment]
> I changed few things about the user links, I tried for an hour to center the buttons but I couldn't do it im pretty sure its easy but can u help?
> 
> ```
>                 <div className="grid relative gap-3 grid-cols-10 max-w-[1000px]">
>                     {!youtube ? null : (
>                         <Link className="w-full transition md:w-[420px] sm:w-[300px] mx-auto h-14 content-center flex items-center justify-center rounded-lg hover:text-white hover:scale-110 relative" target="_blank" href={youtube}><Youtube className="absolute left-6 h-5 w-5"/></Link>
>                     )}
>                     {!insta ? null : (
>                         <Link className="w-full transition md:w-[420px] sm:w-[300px] mx-auto h-14 content-center flex items-center justify-center rounded-lg hover:text-white hover:scale-110 relative" target="_blank" href={insta}><Instagram className="absolute left-6 h-5 w-5"/></Link>
>                     )}
>                     {!face ? null : (
>                         <Link className="w-full transition md:w-[420px] sm:w-[300px] mx-auto h-14 content-center flex items-center justify-center rounded-lg hover:text-white hover:scale-110 relative" target="_blank" href={face}><Facebook className="absolute left-6 h-5 w-5"/></Link>
>                     )}
>                     {!github ? null : (
>                         <Link className="w-full transition md:w-[420px] sm:w-[300px] mx-auto h-14 content-center flex items-center justify-center rounded-lg hover:text-white hover:scale-110 relative" target="_blank" href={github}><Github className="absolute left-6 h-5 w-5"/></Link>
>                     )}
>                 </div>
> ```

just add ` place-items-center` or `place-content-center` in this
 `<div className="grid relative gap-3 grid-cols-10 max-w-[1000px]">`

**Comment by r2hu1** [comment]
and why `grid-cols-10` ?

**Comment by r2hu1** [comment]
dude thats what making it to not be in center the `grid-cols-10` just replace it with `grid-cols-4`
