### ISSUE TITLE
[Security Issue] User email gets exposed.

### ISSUE THREAD

**Issue by legacyxdd** [r2hu1/MySocials#4]
I found an important security vulnerability. The visitor can easily view the user's email using console network tab. I tried to fix this myself but couldn't find a solution.  I think it needs to be fixed immediately, thanks!
![image](https://github.com/user-attachments/assets/5eb60971-4c7a-4d5c-82bf-189aa054be87)

**Comment by r2hu1** [comment]
haha i knew it actually i am thinking to add email in there profile where visitor can directly email them if they want

**Comment by r2hu1** [comment]
if you wanto hide that just remove the email from NextResponse in the api code , i am currently working on https://url-shrtner.vercel.app after it i will update it

**Comment by r2hu1** [comment]
actually i checked it, the schema has email property thats why it is returning it but if you really wanto remove the email return everything except email in `app/api/page/get/route.js` like its returning `return NextResponse.json({ data }, { status: 200 });` change it to `{data.name, data.bio, ....continue}` then it will not return email

**Comment by r2hu1** [comment]
did you added the env variables in vercel project settings? make sure to redeploy after adding it

**Comment by r2hu1** [comment]
can i get the gut url?

**Comment by r2hu1** [comment]
i just imported this repository on vercel dashboard thats it and redeploy after adding env variables
