### ISSUE TITLE
New feature consultation

### ISSUE THREAD

**Issue by domainbf** [r2hu1/MySocials#5]
Hello, the overall function is great. Regarding the login issue, can I set up email and username login? Third-party login is very restrictive without a Google account. Will other login methods be added later?

**Comment by DanielMajolagbe** [comment]
Hello I am facing issues with clerk, Middlewarem And changes i make to the front end are not updating even after i reload the page please help me out when you see this @r2hu1 
![Screenshot (184)](https://github.com/user-attachments/assets/401f02b8-acfd-4c4e-bd26-c23d3c3eba44)

**Comment by r2hu1** [comment]
can you show me the middleware file?

**Comment by DanielMajolagbe** [comment]
![Screenshot (196)](https://github.com/user-attachments/assets/f2294a38-13fb-4167-8033-411e60b10e1a)


The Major problem i'm facing now is that the Changes i make are not reflecting on the browser and its already connected to the localhost but as i am changing the nextjs code it is not reflecting on browser

**Comment by DanielMajolagbe** [comment]
i keep getting this 
```.<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (101kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)```

**Comment by DanielMajolagbe** [comment]
Don't worry man i have figured it out the reason why i was facing this issue is coz i used ```npm start``` instead of ```npm run dev``` i don't know why, but its working already

**Comment by r2hu1** [comment]
great ab about adding more login methods you can enable it on clerk dashboard

**Comment by r2hu1** [comment]
damn your folder icons looks good what extention you are using?

**Comment by DanielMajolagbe** [comment]
Thanks man, it’s material icon theme by philipp Kleif,
